default: &default
  pool: 5
  timeout: 5000
  adapter: sqlite3

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  database: bluefox_db
  host: localhost
  username: bluefox
  port: 5432
  password: qwerty
